version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=jdbc:postgresql://auth-db:5432/authdb
    depends_on:
      - auth-db

  customer-service:
    build: ./customer-service
    ports:
      - "8082:8082"
    environment:
      - DATABASE_URL=jdbc:postgresql://customer-db:5432/customer-db
    depends_on:
      - customer-db

  order-service:
    build: ./order-service
    ports:
      - "8083:8083"
    environment:
      - DATABASE_URL=jdbc:postgresql://order-db:5432/orderdb
    depends_on:
      - order-db

  auth-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  customer-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: customer-db
      POSTGRES_USER: amirgolmoradi
      POSTGRES_PASSWORD: password

  order-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
