version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=jdbc:postgresql://auth-db:5432/authdb
    depends_on:
      - auth-db

  customer-service:
    build:
      context: ./customer-service
    container_name: customer-psql-app
    depends_on:
      - customer-db
    ports:
      - "5332:5432"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://customer-db:5432/customer-psql
      - SPRING_DATASOURCE_USERNAME=amirgolmoradi
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  auth-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'

  customer-db:
    container_name: customer-psql-db
    image: postgres:latest
    environment:
      POSTGRES_DB: customer-psql
      POSTGRES_USER: amirgolmoradi
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'

# Volumes for persistent data storage
volumes:
  mongo-data:
  postgres-data:
