spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: customer-route
          uri: ${CUSTOMER_ROUTE_URI:http://localhost:8081}
          predicates:
            - Path=/customers/**
          filters:
            - PrefixPath=/api/v1
            - AddResponseHeader=X-Powered-By,AmirGol Gateway Service